export const categories = [
  {
    category_id: 1,
    category_name: "Car Talk",
    slug: "car",
    parent_id: null,
    children: [],
  },
  {
    category_id: 2,
    category_name: "Stock",
    slug: "stock",
    parent_id: null,
    children: [],
  },
  {
    category_id: 3,
    category_name: "Real estate",
    slug: "real_estate",
    parent_id: null,
    children: [],
  },
  {
    category_id: 4,
    category_name: "IT",
    slug: "it-science",
    parent_id: null,
    children: [
      {
        category_id: 5,
        category_name: "General/Policy",
        slug: "general_policy",
        parent_id: null,
      },
      {
        category_id: 6,
        category_name: "ICT",
        slug: "ict",
        parent_id: null,
      },
    ],
  },
  {
    category_id: 7,
    category_name: "Industry",
    slug: "industry",
    parent_id: null,
    children: [
      {
        category_id: 8,
        category_name: "Enterprise",
        slug: "company",
        parent_id: null,
      },
    ],
  },
  {
    category_id: 9,
    category_name: "Politics",
    slug: "politics",
    parent_id: null,
    children: [],
  },
  {
    category_id: 10,
    category_name: "Society",
    slug: "society",
    parent_id: null,
    children: [],
  },
  {
    category_id: 11,
    category_name: "International",
    slug: "international",
    parent_id: null,
    children: [],
  },
  {
    category_id: 12,
    category_name: "Science Chosun",
    slug: "science-chosun",
    parent_id: null,
    children: [],
  },
  {
    category_id: 13,
    category_name: "Opinion",
    slug: "opinion",
    parent_id: null,
    children: [],
  },
];
