export const news = [
  {
    news_id: 1,
    category_id: 1,
    title: "First quarter car production, 1 million units in 6 years... more than before corona",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "ParPark Jin-wook Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: true,
  },
  {
    news_id: 2,
    category_id: 1,
    title:
      "Mercedes-Benz Korea launches high-performance electric sedan AMG EQE… 143.8 million won",
    img: "https://biz.chosun.com/resizer/ALf7MpJR54C8_4A6IOZosmGMiIs=/184x104/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/IMY3CFGAJ5DAFED7PSWBB6J6YI.jpg",
    desc: "Mercedes-Benz Korea announced on the 10th that it launched the high-performance electric sedan Mercedes-AMG EQE 53 4Matic+ (Plus). According to Mercedes-Benz Korea, the new car...",
    content: "",
    create_At: "",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
  {
    news_id: 3,
    category_id: 1,
    title:
      "Prosecution, search and seizure of the Fair Trade Commission for suspicion of driving KT work",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
  {
    news_id: 4,
    category_id: 1,
    title:
      "尹 Which company will accompany you on your visit to the United States? Some bio stocks surge",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
  {
    news_id: 5,
    category_id: 1,
    title:
      "Seoul Metropolitan Government supports 1 million won for postpartum care for all pregnant women",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
  {
    news_id: 6,
    category_id: 1,
    title:
      "Should Samsung and LG Electronics be nervous? China's HKC acquires next-generation OLED technology",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
  {
    news_id: 7,
    category_id: 1,
    title:
      "'5 Billion Club' Special Prosecution Act passed by the Judiciary and Son-in-law Committee... 與 collective exit vs. wild single decision",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
  {
    news_id: 8,
    category_id: 1,
    title:
      "Kim Ki-hyun, former President Park Geun-hye's visit in Daegu on the 19th... Schedule in progress",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
  {
    news_id: 9,
    category_id: 1,
    title:
      "Japanese ramen company copied 'Buldak'... Samyang I don't think I need to respond Confidence",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
  {
    news_id: 10,
    category_id: 1,
    title: "“Smartphone alone is not enough” Samsung Electronics partners jumped into the market",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
  {
    news_id: 11,
    category_id: 1,
    title: " To keep your teeth healthy, forget the 3⋅3⋅3 rule Was it a bad habit?",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
  {
    news_id: 12,
    category_id: 1,
    title:
      "Ministry of Culture, Sports and Tourism, building a high-quality corpus of 1 billion words that can create 'Korean chat GPT'",
    img: "https://biz.chosun.com/resizer/-tTb99rm0mMveyJEb5b9SX7AOhE=/400x225/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/DADTCBB4M5DC7D77PWSSUISTYA.jpg",
    desc: "It was found that domestic automobile production in the first quarter of this year was higher than in the first quarter of 2019, before the Corona 19 pandemic. It is analyzed that the semiconductor supply crisis has improved and eco-friendly exports such as electric vehicles have increased. According to the Korea Automobile Manufacturers Association (KAMA) on the 10th, the production of domestic automakers in the first quarter of this year was 1,065,249 units. This is a 27.2% increase from 837,186 units in the same period last year. Compared to the first quarter of 2019 (957,402 units), before the Corona 19 pandemic, it is 11.3% more. Production in the first quarter of this year is the highest in the past five years. First quarter car birth...",
    content: "",
    create_At: "2023-04-10 13:54:19:55",
    creator: "Park Jin-woo",
    views: 100,
    is_hot: true,
    is_show_img: true,
    is_banner: false,
  },
];
