import img from 'public/image/detail-page/picture.png'

export const data = [
    {url:'/image/detail-page/picture.png', alt:'this is image'},
    "From the end of this year at the earliest, it will be possible to compare and recommend various insurance products such as auto insurance and indemnity insurance at a glance on the platform. Financial consumers are expected to be able to sign up for products that are most suitable for them at low prices.",
    "The Financial Services Commission announced on the 6th that it had prepared a plan for pilot operation of insurance products in the platform to enhance the convenience of insurance consumers and promote competition in the insurance industry.",
    "Non-financial companies such as my data operators and electronic financial companies apply for innovative financial services to become a 'platform' that can handle insurance products and compare and recommend insurance products. Under the current insurance business law, only insurance company executives and employees, insurance agents, and insurance solicitors are allowed to recruit, so designation as an innovative financial service is required for platform companies to compare and recommend insurance products.",
    "The Financial Services Commission limited the business scope of the platform to comparing and recommending insurance products during the entire recruitment stage and connecting them to insurance companies. The purpose is to ensure that the platform can compete harmoniously with existing insurance recruitment channels while maximizing consumer benefits such as data analysis.",
     {url:'/image/detail-page/picture1.png', alt:'this is image'},
    "Products that can be handled by the platform are limited to online products (CM). Specifically, among online products, short-term insurance such as travel and fire insurance, auto insurance, indemnity insurance, and savings insurance (excluding pension), which many people subscribe to and have high comparability, are allowed. In addition, products with high potential for market expansion in the future, such as pet insurance and credit life insurance, were included in the permitted list. However, health insurance, etc., which have a risk of incomplete sales due to a complicated product structure, are excluded.",
    "An official from the Financial Services Commission said, “The decision was made after comprehensively considering the characteristics of platform consumers who want easy online insurance subscriptions, the influence of existing recruitment channels such as insurance agents, and product characteristics.” By doing so, we minimized the impact of existing sales channels such as insurance solicitors and insurance agencies.”",
    "The Financial Services Commission also prepared a device to prevent platforms from operating comparison and recommendation algorithms unreasonably. Professional institutions such as Koscom pre-verify the adequacy of the algorithm, and the platform guides consumers to the main points of the algorithm so that consumers can fully understand the factors that affect comparison and recommendation.",
    { url: '/image/detail-page/picture2.png', alt: 'this is image' },
    "The Financial Services Commission also set a fee limit to minimize the transfer of fees received from insurance companies to insurance premiums. For example, the limit of fees for auto insurance premiums is limited to 4%.",
    "The Financial Services Commission has prepared measures to promote fair competition. The platform was prevented from rejecting the insurance company's request for partnership without a justifiable reason, and the platform will notify the insurance company in advance with a sufficient period of time in the event of an important matter.",
    "It is also prohibited for platforms to use their superior position to demand unfair actions from insurance companies. In addition, in order to make the fee provided by the insurance company to the platform transparent, the method of charging the fee must be clearly stated in the consignment contract between the insurance company and the platform, and the act of requesting additional fees other than the contract will be prohibited.",
      "This insurance comparison/recommendation platform service took a considerable period of time to reveal its outline as the differences between the insurance industry and the platform were not narrowed. The most sharply opposed position was on whether or not to allow auto insurance, which has a high proportion of personal insurance agencies, and the fee limit.",
    "Accordingly, the Financial Services Commission formed a working-level task force (TF) in which various stakeholders, including the Financial Supervisory Service, Life Insurance Association, General Insurance Association, Insurance Agency Association, Fintech Industry Association, Korea Consumer Federation, and Insurance Research Institute, were formed to promote broad understanding. Stakeholder opinion was collected. From September of last year to March of this year, six plenary meetings and more than 10 stakeholder relay meetings were held.",
    "The Financial Services Commission plans to designate innovative financial services in June after receiving applications for innovative financial services this month. Consumers are expected to be able to use insurance product comparison and recommendation services through the platform at the end of the year or early next year at the earliest.",
    "The Financial Services Commission said, “During the pilot operation period, we plan to review the system improvement direction by fully analyzing the operation progress, such as the impact of the recruitment market, consumer protection and fair competition.” We will continue to discuss with stakeholders such as agencies, insurance agents, and the platform industry.”",
      
]