import HomeCompany from "@components/company/layout";
import React, { useEffect } from "react";
import Head from "next/head";

type Props = {};

const Index = (props: Props) => {
 
  return (
    <>
      <Head>
        <title>Company website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.svg" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <HomeCompany />
      
    </>
  ); 
};

export default Index;
