import HomeCompany from "@components/company/layout";
import React, { useEffect } from "react";
import { useAppSelector, useAppDispatch } from "@hook/hooks";
import { fetchUsers } from "redux/add/user.action";
import Head from "next/head";

type Props = {};

const Index = (props: Props) => {
 
  return (
    <>
      <Head>
        <title>Company website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.svg" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <HomeCompany />;
    </>
  ); 
};
// Index.getInitialProps = async () => {
//   const res = await fetch('https://api.github.com/repos/vercel/next.js')
//   const json = await res.json()
//   return { stars: json.stargazers_count }
// }
export default Index;
