import React from "react";
import Head from "next/head";
import CustomerCompany from "@components/layouts/layout1/company/customer";

type Props = {};

const Index = (props: Props) => {
  return (
    <>
      <Head>
        <title>Company website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.svg" />
      </Head>
      <CustomerCompany />
    </>
  );
};

export default Index;
