import Head from "next/head";
import { Inter } from "next/font/google";
import HomeLayout1 from "@components/layouts/layout1/view/home/home";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>News website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatar.svg" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&family=Roboto:wght@100;300;700;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <HomeLayout1 />
      </main>
    </>
  );
}
