import Head from "next/head";
import { Inter } from "next/font/google";
import HomeLayout1 from "@components/layouts/layout1/view/home/home";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>News website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatar.svg" />
      </Head>
      <main>
        <HomeLayout1 />
      </main>
    </>
  );
}
