import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@components/common/header/header";
import HomePage from "@components/home/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>News website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <main className="home">
        <Header />
        <HomePage />
      </main>
    </>
  );
}
