import { IComponent } from "@components/dynamic-rendering.interfaces";
//MainTwoColumn
const mockResponsePopular: IComponent = {
  type: "MainLayout",
  data: {
    id: "4400936b-6158-1354-9dc8-a04c57e1af46",
    fluid: true,
    //CategoryHeader
    children: [
      {
        type: "HeaderCommon",
        data: {
          id: "26b3f355-2f65-4aae-b9fd-609779f24fdd2128955",
          title: "A custom title",
          headline: "A random Headline",
          copy: "A really long text....",
          image: {
            url: "https://i.stack.imgur.com/y9DpT.jpg",
          },
        },
      },
      {
        type: "BlockMainWithTab",
        data: {
          id: "26b3f355-2f65-4aae-b9fd-609779f24fdd212",
          isTab: true,
          className: "",
          image: {
            url: "https://i.stack.imgur.com/y9DpT.jpg",
          },
          listNew: [
            {
              adult: false,
              backdrop_path: "/hu2K1XlEyRjO2JvzIHBa6cPQRAi.jpg",
              genre_ids: [9648, 53],
              id: 989473,
              original_language: "en",
              original_title: "Invitation to a Murder",
              overview:
                "1934. South of England. For no apparent reason and like five other unrelated people, Miranda, a 28-year-old florist, is invited for the weekend in the mansion of billionaire Lewis Findley",
              popularity: 97.892,
              poster_path: "/8OyzvMrVx2tXjyJiE3GZpvaXE2T.jpg",
              release_date: "2023-05-05",
              title: "Invitation to a Murder",
              video: false,
              vote_average: 6,
              vote_count: 21,
            },
            {
              adult: false,
              backdrop_path: "/pr5B7Hb7711QQDirAyS5P7fKjts.jpg",
              genre_ids: [53, 28, 27, 12, 18],
              id: 760741,
              original_language: "en",
              original_title: "Beast",
              overview:
                "A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.",
              popularity: 105.243,
              poster_path: "/f18rGcLlawKjNC5KRh36S0mvRlY.jpg",
              release_date: "2022-08-11",
              title: "Beast",
              video: false,
              vote_average: 6.8,
              vote_count: 1099,
            },
            {
              adult: false,
              backdrop_path: "/4uij4drUitClyXihCyQJSklXvvv.jpg",
              genre_ids: [18, 10749],
              id: 876797,
              original_language: "ja",
              original_title: "余命10年",
              overview:
                "The 20-year-old heroine learns that she only has 10 years to live due to an incurable disease of 1 in tens of thousands. She decided not to fall in love and not to be obsessed with living. But then, she met the hero at a local alumni association.",
              popularity: 98.82,
              poster_path: "/yJFUBE5VGjQaTLuyhf4Hb926mn4.jpg",
              release_date: "2022-03-04",
              title: "The Last 10 Years",
              video: false,
              vote_average: 7.1,
              vote_count: 28,
            },
            {
              adult: false,
              backdrop_path: "/kyeqDT2cFhTmwlvtuQY3n2W6Vf3.jpg",
              genre_ids: [28, 53, 12, 27],
              id: 799379,
              original_language: "ko",
              original_title: "늑대사냥",
              overview:
                "While under heavily armed guard, the dangerous convicts aboard a cargo ship unite in a coordinated escape attempt that soon escalates into a bloody, all-out riot. But as the fugitives continue their brutal campaign of terror, they soon discover that not even the most vicious among them is safe from the horror they unknowingly unleashed from the darkness below deck.",
              popularity: 96.752,
              poster_path: "/dniWicB6fa7NvpGbguxWlNPMc5f.jpg",
              release_date: "2022-09-21",
              title: "Project Wolf Hunting",
              video: false,
              vote_average: 6.6,
              vote_count: 130,
            },
            {
              adult: false,
              backdrop_path: "/7TdVWAO7vV9j1OLDq1hQJS3pb4U.jpg",
              genre_ids: [28, 35, 12, 53],
              id: 739405,
              original_language: "en",
              original_title: "Operation Fortune: Ruse de Guerre",
              overview:
                "Special agent Orson Fortune and his team of operatives recruit one of Hollywood's biggest movie stars to help them on an undercover mission when the sale of a deadly new weapons technology threatens to disrupt the world order.",
              popularity: 103.606,
              poster_path: "/uo7vWfQUlVwueYTDRicXOJa8Oow.jpg",
              release_date: "2023-01-04",
              title: "Operation Fortune: Ruse de Guerre",
              video: false,
              vote_average: 6.6,
              vote_count: 715,
            },
            {
              adult: false,
              backdrop_path: "/kZ7unRnWe8UwpJsc1n5venXr9u2.jpg",
              genre_ids: [18, 28],
              id: 619329,
              original_language: "ta",
              original_title: "முந்திரிக்காடு",
              overview:
                "In a Village Where they used to Honor Kill Love couples of the opposite cast and in that village A girl and boy from the opposite cast who used to be friends are getting pressure from village people that they love each other . What happens at the End?\r Whether they succeed or not is the story.",
              popularity: 101.751,
              poster_path: "/k7iEwxmphkr1bwb66CHA4dhyyBF.jpg",
              release_date: "2023-04-07",
              title: "Munthiri Kaadu",
              video: false,
              vote_average: 4.3,
              vote_count: 3,
            },
            {
              adult: false,
              backdrop_path: "/2ZpwPckspTSY9sVEkjEyatgBWT7.jpg",
              genre_ids: [27, 53, 18],
              id: 848058,
              original_language: "es",
              original_title: "Cerdita",
              overview:
                "A bullied overweight teenager sees a glimpse of hope when her tormentors are brutally abducted by a mesmerizing stranger.",
              popularity: 80.667,
              poster_path: "/pIFeu5gF7ofAxI9NqrWbJAjjKn6.jpg",
              release_date: "2022-10-07",
              title: "Piggy",
              video: false,
              vote_average: 6.7,
              vote_count: 375,
            },
            {
              adult: false,
              backdrop_path: "/aAK25IGWGCk33c2rO2eYcek9rIB.jpg",
              genre_ids: [18, 27, 9648, 53],
              id: 934131,
              original_language: "en",
              original_title: "Soft & Quiet",
              overview:
                "Taking place in real time, elementary school teacher Emily organizes a mixer of like-minded women, but an altercation between a woman from Emily’s past and the group leads to a volatile chain of events.",
              popularity: 77.288,
              poster_path: "/hrtO0sVcXolaiIjVoOADO2M24jm.jpg",
              release_date: "2022-11-04",
              title: "Soft & Quiet",
              video: false,
              vote_average: 6,
              vote_count: 54,
            },
            {
              adult: false,
              backdrop_path: "/h1gxz6U2HdDf0AMFXnehz0Muoup.jpg",
              genre_ids: [35, 12, 10751],
              id: 643215,
              original_language: "fr",
              original_title: "Astérix & Obélix : L'Empire du Milieu",
              overview:
                "Gallic heroes and forever friends Asterix and Obelix journey to China to help Princess Sa See save the Empress and her land from a nefarious prince.",
              popularity: 75.93,
              poster_path: "/ifOqT5SmA4ANjmyEacLw3KAFKUd.jpg",
              release_date: "2023-02-01",
              title: "Asterix & Obelix: The Middle Kingdom",
              video: false,
              vote_average: 4.8,
              vote_count: 338,
            },
            {
              adult: false,
              backdrop_path: "/f76pf0QxldYY8mMHW4kudXhuLZB.jpg",
              genre_ids: [18, 36],
              id: 916386,
              original_language: "de",
              original_title: "Der Passfälscher",
              overview:
                "Jewish aesthete Cioma, 21, does not let anyone take away his joy of life, especially not the Nazis. In 1942, he has to find new ways to make his living in Berlin and escape deportation. In the process he discovers his talent for forgery: not only with passports, but also his own identity.",
              popularity: 61.662,
              poster_path: "/iJmVqG9y156lRObOEIAOnAEnAnz.jpg",
              release_date: "2022-10-13",
              title: "The Forger",
              video: false,
              vote_average: 6.5,
              vote_count: 11,
            },
            {
              adult: false,
              backdrop_path: "/9zXPnbVpaDfTniLBuc5vgXGfzAP.jpg",
              genre_ids: [28, 53, 80],
              id: 818397,
              original_language: "en",
              original_title: "Memory",
              overview:
                "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
              popularity: 76.19,
              poster_path: "/4Q1n3TwieoULnuaztu9aFjqHDTI.jpg",
              release_date: "2022-04-28",
              title: "Memory",
              video: false,
              vote_average: 7,
              vote_count: 1209,
            },
            {
              adult: false,
              backdrop_path: "/rCZNtFhCId7zAMo68xyCEwnRvB.jpg",
              genre_ids: [18],
              id: 901563,
              original_language: "fr",
              original_title: "Close",
              overview:
                "Two thirteen year-olds have always been incredibly close but they drift apart after the intimacy of their relationship is questioned by schoolmates.  An emotionally transformative and unforgettable portrait of the intersection of friendship and love, identity and independence, and heartbreak and healing.",
              popularity: 71.25,
              poster_path: "/j7ReE0UZ9sgtfLvzszMgQw8Mxb2.jpg",
              release_date: "2022-11-01",
              title: "Close",
              video: false,
              vote_average: 7.8,
              vote_count: 378,
            },
            {
              adult: false,
              backdrop_path: "/oMsoN3RsJEjxOWcImvwTffEnkMd.jpg",
              genre_ids: [16, 10751],
              id: 987750,
              original_language: "es",
              original_title: "Inspector Sun y la maldición de la viuda negra",
              overview:
                "Shanghai, 1934. In an insect world parallel to that of humans, veteran Inspector Sun, a lone spider, leads his last mission against his archenemy the Red Locust, before embarking on a well-deserved retirement. His vacation aboard a Pan Am clipper between Shanghai and San Francisco comes to an abrupt end when millionaire Dr. Spindelthorp is found murdered. What begins as a routine case for Sun will ultimately decide the fate of humanity.",
              popularity: 63.897,
              poster_path: "/v1Wj5lzvsvFbXHdrmYGdXL10Q73.jpg",
              release_date: "2022-12-28",
              title: "Inspector Sun and the Curse of the Black Widow",
              video: false,
              vote_average: 6.8,
              vote_count: 123,
            },
            {
              adult: false,
              backdrop_path: "/dbrLfmFNFEJWv8rLnjpgCKlXWSy.jpg",
              genre_ids: [878, 12, 28],
              id: 333339,
              original_language: "en",
              original_title: "Ready Player One",
              overview:
                "When the creator of a popular video game system dies, a virtual contest is created to compete for his fortune.",
              popularity: 59.964,
              poster_path: "/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg",
              release_date: "2018-03-28",
              title: "Ready Player One",
              video: false,
              vote_average: 7.6,
              vote_count: 14031,
            },
            {
              adult: false,
              backdrop_path: "/bGfbeZ52aqTvxde9pjyC62jaSUg.jpg",
              genre_ids: [18],
              id: 919570,
              original_language: "ro",
              original_title: "R.M.N.",
              overview:
                "A few days before Christmas, having quit his job in Germany, Matthias returns to his Transylvanian village. He wishes to involve himself more in the education of his son, Rudi, left for too long in the care of his mother, Ana, and to rid him of the unresolved fears that have gripped him. He’s also eager to see his ex-lover Csilla and preoccupied about his old father, Otto. When a few new workers are hired at the small factory that Csilla manages, the peace of the community is disturbed, underlying fears grip the adults, and frustrations, conflicts and passions erupt through the thin sliver of apparent understanding and calm.",
              popularity: 55.975,
              poster_path: "/kDcEfgF7CUo0IYLIazUYYqxagTG.jpg",
              release_date: "2022-06-03",
              title: "R.M.N.",
              video: false,
              vote_average: 6.9,
              vote_count: 67,
            },
            {
              adult: false,
              backdrop_path: "/8c9c4xg0IdXDg627uQF35K54VpC.jpg",
              genre_ids: [10749, 35],
              id: 800301,
              original_language: "en",
              original_title: "What's Love Got to Do with It?",
              overview:
                "Two childhood friends now in their thirties must decide whether to follow their heads or their hearts once the man decides to follow his parents' advice and enter into an arranged marriage in Pakistan.",
              popularity: 61.448,
              poster_path: "/14fGGPAL5PQxuesjO4CFoDJEH5G.jpg",
              release_date: "2023-01-26",
              title: "What's Love Got to Do with It?",
              video: false,
              vote_average: 6.3,
              vote_count: 56,
            },
            {
              adult: false,
              backdrop_path: "/jENycYiYGr5NvMs789zj06JkW5l.jpg",
              genre_ids: [35, 18],
              id: 497828,
              original_language: "en",
              original_title: "Triangle of Sadness",
              overview:
                "A celebrity model couple are invited on a luxury cruise for the uber-rich, helmed by an unhinged, alcoholic captain. What first appears Instagrammable ends catastrophically, leaving the survivors stranded on a desert island in a struggle of hierarchy.",
              popularity: 62.457,
              poster_path: "/k9eLozCgCed5FGTSdHu0bBElAV8.jpg",
              release_date: "2022-09-18",
              title: "Triangle of Sadness",
              video: false,
              vote_average: 7.2,
              vote_count: 1283,
            },
            {
              adult: false,
              backdrop_path: "/tbQ7bEg5qnk7zR1bsi4xMqnaIRu.jpg",
              genre_ids: [80, 9648, 53],
              id: 536437,
              original_language: "en",
              original_title: "Hypnotic",
              overview:
                "A detective becomes entangled in a mystery involving his missing daughter and a secret government program while investigating a string of reality-bending crimes.",
              popularity: 48.503,
              poster_path: "/mv362kHXz4Yr33wtQhqfcJWFM8G.jpg",
              release_date: "2023-05-11",
              title: "Hypnotic",
              video: false,
              vote_average: 6.9,
              vote_count: 10,
            },
            {
              adult: false,
              backdrop_path: "/1jCXk512KPr6MzXEZf7UH4fbtba.jpg",
              genre_ids: [35, 18],
              id: 800787,
              original_language: "en",
              original_title: "A Good Person",
              overview:
                "Allison's life falls apart following her involvement in a fatal accident. The unlikely relationship she forms with her would-be father-in-law helps her live a life worth living.",
              popularity: 56.631,
              poster_path: "/6toz74j1OgbQrsZUjgr2Ohs1AsE.jpg",
              release_date: "2023-03-23",
              title: "A Good Person",
              video: false,
              vote_average: 6.9,
              vote_count: 59,
            },
            {
              adult: false,
              backdrop_path: "/k88X6FXbypxL6OeoV5bDcTK1gfM.jpg",
              genre_ids: [9648, 53, 80],
              id: 844417,
              original_language: "en",
              original_title: "Marlowe",
              overview:
                "Private detective Philip Marlowe becomes embroiled in an investigation involving a wealthy Californian family after a beautiful blonde hires him to track down her former lover.",
              popularity: 62.019,
              poster_path: "/vjAMj81oYBryzGBhJk4gcK0M636.jpg",
              release_date: "2023-02-15",
              title: "Marlowe",
              video: false,
              vote_average: 6.1,
              vote_count: 113,
            },
          ],
          children: [
            {
              type: "CardRowMain",
              data: {
                id: "26b3f355-2f65-4aae-b9fd-609779f24fdd212",
                title: "A custom title",
                headline: "A random Headline",
                copy: "A really long text....",
                image: {
                  url: "https://i.stack.imgur.com/y9DpT.jpg",
                },
              },
            },
            {
              type: "CardRow",
              data: {
                id: "4400936b-6158-9087-9dc8-a04c57e1af46121x21212131",
                title: "CardTextTitle add",
                className: "border",
              },
            },
            {
              type: "BoxCategory",
              data: {
                id: "4400936b-6158-9087-9dc8-a04c57e1af46121x2121213",
                className: "clslistcategory-item2",
                sx: { paddingTop: 0, paddingBottom: 0, position: "sticky", top: "66px" },
                children: [
                  {
                    type: "TabContainer",
                    data: {
                      id: "4400936b-6158-4943-9dc8-a04c57e1af461",
                      title: "Title",
                      headline: "This can be anything",
                      copy: "A really long text....",

                      image: {
                        url: "https://i.stack.imgur.com/y9DpT.jpg",
                      },
                      tabTitle: ["LastNews", "News"],
                      datanew: {
                        LastNews: [
                          {
                            id: "4400936b-6158-4943-9dc8-a04c57e1af46121",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                          {
                            id: "4400936b-6158-4943-9dc8-a04c57e121af461",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                          {
                            id: "4400936b-6158-4943-9dc8-a0412c57e1af461",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                          {
                            id: "4400936b-6158-4943-9dc8-a04121c57e1af461",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                          {
                            id: "4400936b-6158-4943-9dc8-a0412c57e1af461",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                          {
                            id: "4400936b-6158-4943-9dc8-a04121c57e1af461",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                        ],
                        News: [
                          {
                            id: "4400936b-6158-4943-9dc8-a04c57e19af4611",
                            title: "Title New 2222222",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                          {
                            id: "4400936b-6158-4943-9dc8-a04c5776e121af461",
                            title: "Title 121344",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                          {
                            id: "4400936b-6158-4943-9dc8-a041u72c57e1af461",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                          {
                            id: "4400936b-6158-4943-9dc8-a0412166c57e1af461",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                          {
                            id: "4400936b-6158-4943-9dc8-a0412c57e1af461",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                          {
                            id: "4400936b-6158-4943-9dc8-a04121c57e1af461",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            item: {},
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                        ],
                      },

                      children: [
                        {
                          type: "CardTextTitle",
                          data: {
                            id: "4400936b-6158-4943-9dc8-a04c57e1af46y712",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            items: {
                              title: "string",
                              urlImg: "https://i.stack.imgur.com/y9DpT.jpg",
                              description: "string description",
                              author: "string Jonh",
                              createDay: new Date(),
                              publishDay: new Date(),
                              className: " container2", // enum list
                              id: "4400936b-6158-string", // call api detail
                              slug: "string-this-is article", // change params url ,
                              overview: " string-this-is article___ overview",
                            },
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                        },
                        {
                          type: "BoxCard",
                          data: {
                            id: "4400936b-6158-9087-9dc8-a04c57e1af46121x212",
                            title: "CardTextTitle example",
                            className: "btn-primary",
                            action: {
                              type: "call",
                              url: "https://pokeapi.co/api/v2/",
                            },
                          },
                        },
                        {
                          type: "CardTextTitle",
                          data: {
                            id: "4400936b-6158-4943-9dc8-a04c57e1af46y7",
                            title: "Title",
                            headline: "This can be anything",
                            copy: "A really long text....",
                            image: {
                              url: "https://i.stack.imgur.com/y9DpT.jpg",
                            },
                          },
                        },
                      ],
                    },
                  },
                ],
              },
            },
            {
              type: "TabColumn",
              data: {
                id: "26b3f355-2f121265-4aae-b9fd-609779f24fdd12122",
                title: "A custom title",
                headline: "A random Headline",
                copy: "A really long text....",
                action: {
                  type: "call",
                  url: "https://pokeapi.co/api/v2/",
                },
              },
            },
          ],
        },
      },
    ],
  },
};

export default mockResponsePopular;
